config/routes.rb
Rails.application.routes.draw do
  root to: "contacts#index"
  resources :contacts, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  enum answer_to_return: {"電話" => 0, "メール" => 1}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all
  end

  def new
    @answer = Contact.answer_to_returns
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      redirect_to root_path, notice: '送信されました'
    end
  end

  private
    def contact_params
      params.require(:contact).permit(:name, :email, :subject, :phone_numb, :message, :answer_to_return)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/index.html.erb
<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Subject</th>
      <th>Phone numb</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.subject %></td>
        <td><%= contact.phone_numb %></td>
        <td><%= contact.message %></td>
        <td><%= contact.answer_to_return %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= form_with model: @contact, local: true do |f| %>

  <div class="field form-group">
    <%= f.label :name, "名前" %>
    <%= f.text_field :name, 
      autofocus: true,
      autocpomplete: "name",
      placeholder: "タイトル",
      required: "",
      class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :email, "メールアドレス" %>
    <%= f.email_field :email, 
      autofocus: true,
      autocpomplete: "E-mail",
      required: "",
      class:"form-control" %>
  </div>
  
  <div class="field form-group">
    <%= f.label :subject, "件名" %>
    <%= f.text_field :subject, 
      autofocus: true,
      autocpomplete: "Subject",
      required: "",
      class:"form-control" %>
  </div>
  
  <div class="field form-group">
    <%= f.label :phone_numb, "電話番号" %>
    <%= f.telephone_field :phone_numb, 
      autofocus: true,
      autocpomplete: "Phone Number",
      required: "",
      class:"form-control" %>
  </div>


  <div class="field form-group">
    <%= f.label :message, "お問い合わせ内容" %>
    <%= f.text_area :message,
      autofocus: true,
      autocpomplete: "message",
      required: "",
      rows: "5",
      class:"form-control" %>
  </div>
  
  <div class="field form-group">
    <%= f.label :answer_to_return, '折返し方法' %>
    <%= f.select :answer_to_return, @answer.keys.map {|k| [k, k]}, {prompt:"選択してください"}, { class: 'form-control', required: "" } %>
  </div>

  <div class="actions">
    <%= f.submit "送信", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MailTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class = "container">
      <%= yield %>
    </div>
  </body>
</html>